### PR TITLE
Feature/id list and window size

### PR DESCRIPTION
**Pull request by JMZach**
A few new things here:
- changed how the build system works to support ESM and CJS - (should support JSX now)
- `useIdList` for managing arrays of objects that all have id's
- pulled `useWindowSize` out of a project to add here - works SSR wise - there is a context version as well
- I've moved the files that are built into a separate folder/s - as the imports will now be different we may need to bump the version number high enough to avoid breaking changes landing in peoples deployments.

### CODE REVIEW

**Comment by floatingdino** [comment]
@JMZach love your work -- the reason I was compiling to the root is so that each hook has its own file. Classically, compilers struggle to tree-shake functions that are exposed from the same file (eg: importing one hook from the hooks index will include all of them in the bundle). Things might be better now, but I haven't seen it yet - could you run some tests to make sure that importing a named function from the index bundle doesn't include all of them in the code?

**Comment by JMZach** [comment]
@floatingdino
the tree-shake-ing was an interesting rabbit hole. I've had to make a few more changes to get it to run correctly with how `Typescript barrel files` work.

By specifying this in `package.json`
```json
"sideEffects": false,
"exports": {
    ".": {
      "require": "./lib/cjs/index.js",
      "import": "./lib/esm/index.js",
      "types": "./lib/esm/index.d.ts"
    }
  }
```
And adding `tsconfig.json`

```json
"isolatedModules": true,
 "declarationMap": true,
```
And import/export like this in the index file:
```tsx
export { default as useMouseCoords } from "./useMouseCoords"
export { default as useDraggable } from "./useDraggable"
export { WindowSizeContext, WindowSizeProvider } from "./useWindowSizeContext"
export { default as useWindowSize } from "./useWindowSize"
export {
  default as useIdList,
  idListById,
  idListLargestId,
  idListSmallestId,
  idListAsMap,
  idMapAsList,
  idListUnique
} from "./useIdList"
```

importing should now pull from the ESM folder and at least in nextjs using ^10.2.x it should should properly tree-shake it. With nextjs 12.2.x I was able to run a build and only the parts that were imported were added to the build. 

If you'd prefer to stick with just the ESM in the root folder I'm happy to go back to that and ditch the cjs.

**Comment by floatingdino** [comment]
@JMZach interesting! I haven't tried that before - would you mind splitting out the compiler changes into a different PR, I have some separate comments about the new hooks you're introducing here that I'd rather address separately.

**Comment by JMZach** [comment]
@floatingdino Sure no worries - I've got some time today to have a look.

**Comment by floatingdino** [comment]
@JMZach you'll need to merge in `main` to continue on this one

**Pull request closed without merging**
